### ISSUE TITLE
오류가 나네요.!

### ISSUE THREAD

**Issue by bsshin71** [J0131/SRT_MACRO#1]
1. 크롬버전 : 버전 120.0.6099.225(공식 빌드) (64비트)
2. 크롬 driver 버전 : https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.85/win64/chromedriver-win64.zip
3. 실행 : Pycharm 에서 VitualEnv 환경에서 실행했습니다.
4. 오류내용: 
--------------- Start SRT Macro ---------------
Traceback (most recent call last):
  File "C:\Users\D-bsshin\PycharmProjects\SRT_MACRO\env\Lib\site-packages\selenium\webdriver\common\driver_finder.py", line 38, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\D-bsshin\PycharmProjects\SRT_MACRO\env\Lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 87, in driver_location
    browser = options.capabilities["browserName"]
              ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'capabilities'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\D-bsshin\PycharmProjects\SRT_MACRO\main.py", line 35, in <module>
    driver = webdriver.Chrome("chromedriver")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\D-bsshin\PycharmProjects\SRT_MACRO\env\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\D-bsshin\PycharmProjects\SRT_MACRO\env\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 49, in __init__
    self.service.path = DriverFinder.get_path(self.service, options)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\D-bsshin\PycharmProjects\SRT_MACRO\env\Lib\site-packages\selenium\webdriver\common\driver_finder.py", line 40, in get_path
    msg = f"Unable to obtain driver for {options.capabilities['browserName']} using Selenium Manager."
                                         ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'capabilities'

5. 뭐가 잘못된 것일까요????

**Comment by gpdnjs0215** [comment]
driver = webdriver.Chrome()

로 고쳐주면 됩니다. ("chromedriver" 변수 삭제)

**Comment by J0131** [comment]
최신 버전의 selenium에서는 더 이상 크롬 드라이버의 load가 필요하지 않아

driver = webdriver.Chrome("chromedriver")  
=>  driver = webdriver.Chrome() 

코드를 위와 같이 변경해주시면 됩니다.
