### ISSUE TITLE
오류 

### ISSUE THREAD

**Issue by kj2341** [J0131/SRT_MACRO#4]
--------------- Start SRT Macro ---------------
selenium version :  4.20.0
Traceback (most recent call last):
  File "C:\Users\임시\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\driver_finder.py", line 67, in _binary_paths
    output = SeleniumManager().binary_paths(self._to_args())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\임시\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 53, in binary_paths
    return self._run(args)
           ^^^^^^^^^^^^^^^
  File "C:\Users\임시\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 118, in _run
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: C:\Users\임시\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome --language-binding python --output json; code: 69
{'code': 69, 'message': 'Driver unavailable: Driver path: ', 'driver_path': '', 'browser_path': ''}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\임시\Desktop\SRT_MACRO-main\SRT_MACRO-main\main.py", line 42, in <module>
    driver = webdriver.Chrome() if int(v1) < 4 else webdriver.Chrome()
                                                    ^^^^^^^^^^^^^^^^^^
  File "C:\Users\임시\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\임시\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 50, in __init__
    if finder.get_browser_path():
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\임시\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\driver_finder.py", line 47, in get_browser_path
    return self._binary_paths()["browser_path"]
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\임시\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\driver_finder.py", line 78, in _binary_paths
    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

혹시 어떤게 문제인지 알 수 있을까요 ?

**Comment by J0131** [comment]
chromdriver.exe 파일의 경로 문제가 가장 유력해보입니다.

우선 main.py가 위치한 폴더에 사용하시는 크롬 버전과 맞는 chromedriver.exe 파일을 위치시키고 다시 한번 말씀해주시겠어요?

**Comment by kj2341** [comment]
위치시키고 버전도 동일한 상태인데 제가 걸리는 부분은,

idle로 main.py 을 열었을 때
--
chrome_path = 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe %s'

############# 자동 예매 원하는 설정으로 변경 ##############
--
여기서 크롬 패치 = ~~~
이 부분 경로를 그대로 따라 들어가니
저는 C:\Program Files (x86)\Google 이후에 /chrome이라는 폴더가 존재하지 않는 상태입니다. 
그래서 이 부분에서 오류가 있는게 아닐까 생각하는데.. 해결방법이 없을까요
